# Generated by Django 2.2.4 on 2019-09-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('url', models.URLField(verbose_name='url do video')),
                ('description', models.TextField(verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'Conteúdo',
                'verbose_name_plural': 'Conteúdos',
                'ordering': ['order'],
            },
        ),
    ]
