# Generated by Django 2.2.4 on 2020-07-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200708_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoria', models.CharField(blank=True, max_length=40)),
                ('produto', models.CharField(blank=True, max_length=40, null=True)),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ManyToManyField(blank=True, related_name='produto_categoria', to='content.Categoria')),
            ],
        ),
    ]
