# Generated by Django 2.2.4 on 2020-07-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200708_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='fins_lucrativos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='subtipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='tipo_de_porte',
            field=models.CharField(choices=[('PQ', 'Pequeno'), ('MD', 'Médio'), ('GD', 'Grande'), ('GG', 'Gigante')], default='PQ', max_length=2),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='transparencia_financeira',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='vinculo_com_grandes_corporacoes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='vinculo_com_organizacoes_sociais',
            field=models.BooleanField(default=True),
        ),
    ]
